### ISSUE TITLE
API break between rmp-serde 0.14.0 and 0.14.2?

### ISSUE THREAD

**Issue by vext01** [3Hren/msgpack-rust#237]
I've recently encountered compilation breakage when upgrading from 0.14.0 to 0.14.2:

```
error[E0107]: wrong number of type arguments: expected 2, found 1
  --> ykpack/src/encode.rs:11:10
   |
11 |     ser: Serializer<&'a mut dyn Write>,
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 2 type arguments
```

This is because `Serializer` had a new type parameter `C` added.

Shouldn't 0.14.x have been bumped to 0.15.0 at the time this was introduced?

**Comment by kornelski** [comment]
That was unintentional. I'll yank and bump version.

**Comment by vext01** [comment]
Thanks!

I'd also appreciate some documentation on how to pass around serializers that use the new `C` type parameter. I'm totally failing!

Minimal example:
```
#![allow(unused_imports, dead_code)]

use rmp_serde::{encode, Serializer, config::{SerializerConfig, DefaultConfig}};
use std::io::Write;
use std::fs::File;

struct S<'a, C> {
    ser: Serializer<&'a mut dyn Write, C>,
}

impl<'a, C> S<'a, C> {
    fn new(w: &'a mut dyn Write) -> Self {
        Self { ser: Serializer::new(w) }
    }
}

fn main() {
    println!("Hello, world!");

    let s = S::new(&mut File::create("/tmp/abc").unwrap());
}
```

Gives:
```
error[E0308]: mismatched types
  --> src/main.rs:13:21
   |
11 | impl<'a, C> S<'a, C> {
   |          - this type parameter
12 |     fn new(w: &'a mut dyn Write) -> Self {
13 |         Self { ser: Serializer::new(w) }
   |                     ^^^^^^^^^^^^^^^^^^ expected type parameter `C`, found struct `rmp_serde::config::DefaultConfig`
   |
   = note: expected struct `rmp_serde::encode::Serializer<&'a mut (dyn std::io::Write + 'a), C>`
              found struct `rmp_serde::encode::Serializer<&mut (dyn std::io::Write + 'a), rmp_serde::config::DefaultConfig>`
   = help: type parameters must be constrained to match other types
   = note: for more information, visit https://doc.rust-lang.org/book/ch10-02-traits.html#traits-as-parameters

error[E0282]: type annotations needed for `S<'_, C>`
  --> src/main.rs:20:13
   |
20 |     let s = S::new(&mut File::create("/tmp/abc").unwrap());
   |         -   ^^^^^^ cannot infer type for type parameter `C`
   |         |
   |         consider giving `s` the explicit type `S<'_, C>`, where the type parameter `C` is specified

error: aborting due to 2 previous errors
```

What's the correct way to do this?

**Comment by kornelski** [comment]
That code doesn't compile with 0.14.0 either?

**Comment by kornelski** [comment]
Serializer::new() doesn't allow customization of the `C` parameter. I don't see any way to customize it.

**Comment by vext01** [comment]
I wouldn't expect it to, as the `C` parameter is not present in 0.14.0. I'm (for now) using the yanked 0.14.2 with `C`.

This seems to work:
```
#![allow(unused_imports, dead_code)]

use rmp_serde::{encode, Serializer, config::{SerializerConfig, DefaultConfig}};
use std::io::Write;
use std::fs::File;

struct S<'a> {
    ser: Serializer<&'a mut dyn Write, DefaultConfig>,
}

impl<'a> S<'a> {
    fn new(w: &'a mut dyn Write) -> Self {
        Self { ser: Serializer::new(w) }
    }
}

fn main() {
    println!("Hello, world!");

    let s = S::new(&mut File::create("/tmp/abc").unwrap());
}
```

To make `S` parametrised over any config, I think this is then correct:
```
#![allow(unused_imports, dead_code)]

use rmp_serde::{encode, Serializer, config::{SerializerConfig, DefaultConfig}};
use std::io::Write;
use std::fs::File;

struct S<'a> {
    ser: Serializer<&'a mut dyn Write, DefaultConfig>,
}

impl<'a> S<'a> {
    fn new(w: &'a mut dyn Write) -> Self {
        Self { ser: Serializer::new(w) }
    }
}

fn main() {
    println!("Hello, world!");

    let s = S::new(&mut File::create("/tmp/abc").unwrap());
}
```

So this is a case of user error. I've been using rust for over 2 years and I still find the type/trait system baffling complicated to understand.

Sorry for the noise.

**Comment by vext01** [comment]
Since 0.14.2 was now pulled, I think we can close this.

**Comment by vext01** [comment]
Oops. It's not yanked yet, is it.

https://crates.io/crates/rmp-serde/0.14.2

**Comment by kornelski** [comment]
Since it's not actually an API break, I've restored 0.14.2.

**Comment by vext01** [comment]
It prevents existing code from compiling though. Surely that's an API break?

**Comment by kornelski** [comment]
Ah, sorry. I focused on the Serializer::new issue. 

I'll add default value for the second arg, which should fix it I think.

**Comment by kornelski** [comment]
Released a fix
